print("employee details")
name=str(input("enter employee name:"))
age=int(input("enter employee age:"))
id=str(input("enter employee id:"))
salary=float(input("enter employee salary:"))
exp=float(input("enter employee experience:"))
print("employee details are:")
print(f"EMPLOYEE NAME :{name}")
print(f"EMPLOYEE AGE :{age}")
print(f"EMPLOYEE ID: {id}")
print(f"EMPLOYEE SALARY :{salary}")
print(f"EMPLOYEE EXPERIENCE : {exp}")